export const COOKIE_AUTH = "COOKIE_AUTH_APP";
export const COOKIE_REFRESH = "COOKIE_REFRESH_APP";
export const COOKIE_CODE = "COOKIE_CODE";
export const STORAGE_CURRENT_PHONE = "STORAGE_CURRENT_PHONE";